#include "ft_printf.h"
#include <stdio.h>
#include <unistd.h>

int	main(void)
{
	ft_printf("\n---------- (%%10p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%10p] |", NULL));
	ft_printf("\n---------- (%%010p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%010p] |", NULL));
	ft_printf("\n---------- (%%.0p); p = NULL ----------\n");
 	ft_printf("=> [%d]\n", ft_printf("[%.0p] |", NULL));
	ft_printf("\n---------- (%%1.0p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%1.0p] |", NULL));
	ft_printf("\n---------- (%%2.0p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%2.0p] |", NULL));
	ft_printf("\n---------- (%%3.0p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%3.0p] |", NULL));
	ft_printf("\n---------- (%%4.0p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%4.0p] |", NULL));
	ft_printf("\n---------- (%%10.0p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%10.0p] |", NULL));
	ft_printf("\n---------- (%%.1p); p = NULL ----------\n");
 	ft_printf("=> [%d]\n", ft_printf("[%.1p] |", NULL));
	ft_printf("\n---------- (%%1.1p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%1.1p] |", NULL));
	ft_printf("\n---------- (%%2.1p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%2.1p] |", NULL));
	ft_printf("\n---------- (%%3.1p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%3.1p] |", NULL));
	ft_printf("\n---------- (%%4.1p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%4.1p] |", NULL));
	ft_printf("\n---------- (%%10.1p); p = NULL ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%10.1p] |", NULL));

	char	*point_var;
	ft_printf("\n---------- (%%10p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%10p] |", point_var));
	ft_printf("\n---------- (%%010p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%010p] |", point_var));
	ft_printf("\n---------- (%%.0p); p = point_var ----------\n");
 	ft_printf("=> [%d]\n", ft_printf("[%.0p] |", point_var));
	ft_printf("\n---------- (%%1.0p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%1.0p] |", point_var));
	ft_printf("\n---------- (%%2.0p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%2.0p] |", point_var));
	ft_printf("\n---------- (%%3.0p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%3.0p] |", point_var));
	ft_printf("\n---------- (%%4.0p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%4.0p] |", point_var));
	ft_printf("\n---------- (%%10.0p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%10.0p] |", point_var));
	ft_printf("\n---------- (%%.1p); p = point_var ----------\n");
 	ft_printf("=> [%d]\n", ft_printf("[%.1p] |", point_var));
	ft_printf("\n---------- (%%1.1p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%1.1p] |", point_var));
	ft_printf("\n---------- (%%2.1p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%2.1p] |", point_var));
	ft_printf("\n---------- (%%3.1p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%3.1p] |", point_var));
	ft_printf("\n---------- (%%4.1p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%4.1p] |", point_var));
	ft_printf("\n---------- (%%10.1p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%10.1p] |", point_var));
	ft_printf("\n---------- (%%.3p); p = point_var ----------\n");
 	ft_printf("=> [%d]\n", ft_printf("[%.3p] |", point_var));
	ft_printf("\n---------- (%%1.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%1.3p] |", point_var));
	ft_printf("\n---------- (%%2.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%2.3p] |", point_var));
	ft_printf("\n---------- (%%3.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%3.3p] |", point_var));
	ft_printf("\n---------- (%%4.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%4.3p] |", point_var));
	ft_printf("\n---------- (%%10.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%10.3p] |", point_var));
	ft_printf("\n---------- (%%.3p); p = point_var ----------\n");
 	ft_printf("=> [%d]\n", ft_printf("[%.3p] |", point_var));
	ft_printf("\n---------- (%%1.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%1.3p] |", point_var));
	ft_printf("\n---------- (%%2.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%2.3p] |", point_var));
	ft_printf("\n---------- (%%3.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%3.3p] |", point_var));
	ft_printf("\n---------- (%%4.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%4.3p] |", point_var));
	ft_printf("\n---------- (%%10.3p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%10.3p] |", point_var));
	ft_printf("\n---------- (%%.20p); p = point_var ----------\n");
 	ft_printf("=> [%d]\n", ft_printf("[%.20p] |", point_var));
	ft_printf("\n---------- (%%1.20p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%1.20p] |", point_var));
	ft_printf("\n---------- (%%2.20p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%2.20p] |", point_var));
	ft_printf("\n---------- (%%3.20p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%3.20p] |", point_var));
	ft_printf("\n---------- (%%4.20p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%4.20p] |", point_var));
	ft_printf("\n---------- (%%10.20p); p = point_var ----------\n");
	ft_printf("=> [%d]\n", ft_printf("[%10.20p] |", point_var));

	return (0);
}
